services:
  civicrm:
    image: valuablesquirrel/drupal-civicrm:latest
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - DRUPAL_ADMIN_USER=admin
      - DRUPAL_ADMIN_PASSWORD=admin
      - CIVICRM_SITE_NAME="Wanaoni Family"
      - CIVICRM_ADMIN_EMAIL=admin@wanaoni.org

  db:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - civicrm-db-data:/var/lib/mysql

volumes:
  civicrm-db-data:

